const colors = {
  light: {
    text: "#111B21",
    tint: "#075E54",
    background: "#ECE5DD",
    foreground: "#111B21",
    card: "#FFFFFF",
    cardForeground: "#111B21",
    primary: "#075E54",
    primaryForeground: "#FFFFFF",
    secondary: "#25D366",
    secondaryForeground: "#FFFFFF",
    muted: "#F0F2F5",
    mutedForeground: "#667781",
    accent: "#DCF8C6",
    accentForeground: "#111B21",
    destructive: "#EA0038",
    destructiveForeground: "#FFFFFF",
    border: "#E9EDEF",
    input: "#E9EDEF",
    header: "#075E54",
    headerText: "#FFFFFF",
    outgoingBubble: "#DCF8C6",
    incomingBubble: "#FFFFFF",
    statusGreen: "#25D366",
    statusYellow: "#FFC107",
    statusRed: "#EA0038",
    chatBg: "#ECE5DD",
    unreadBadge: "#25D366",
    tabBar: "#F0F2F5",
    searchBg: "#FFFFFF",
    inputBg: "#FFFFFF",
    sendBtn: "#075E54",
    tick: "#34B7F1",
    divider: "#E9EDEF",
  },
  radius: 10,
};

export default colors;
