name: Build and Package Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # تثبيت pnpm كأداة فقط وليس للتثبيت
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Force Install Dependencies with NPM
      run: |
        rm -f pnpm-lock.yaml
        npm install --force

    - name: Build project
      # الآن pnpm موجود، وسينفذ الأمر البرمجي بنجاح
      run: pnpm run build --if-present

    - name: Upload Production Build
      uses: actions/upload-artifact@v4
      with:
        name: WhatsApp-Project-Files
        path: .
