name: Build and Package Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Clear pnpm cache and Install
      run: |
        # تنظيف أي إعدادات سابقة وتحديد وضع الحلول الأعلى
        pnpm config set resolution-mode highest
        # حذف الذاكرة التخزين المؤقت لضمان عدم سحب بيانات تالفة
        pnpm store prune
        # التثبيت مع تجاهل ملف القفل تماماً وبناء سجل جديد
        pnpm install --no-frozen-lockfile --ignore-scripts --prefer-offline=false

    - name: Build project
      run: pnpm run build --if-present

    - name: Upload Production Build
      uses: actions/upload-artifact@v4
      with:
        name: WhatsApp-Project-Files
        path: .
